### ISSUE TITLE
About release scheme

### ISSUE THREAD

**Issue by chenrui333** [bokwoon95/wgo#13]
👋 while [reviewing the homebrew PR](https://github.com/Homebrew/homebrew-core/pull/199646), I noticed that the project does not use semantic versioning, any reason why? Thanks!

**Comment by bokwoon95** [comment]
sorry, that was just me trying to get the GitHub Actions build.yml script to work. I had to create a new release every time because that was how I tested the Action (functionally, v0.5.6d/v0.5.6c/v0.5.6b/v0.5.6a/v0.5.6 are all identical because the code didn't change).

The next release will continue with semantic versioning.

**Comment by chenrui333** [comment]
@bokwoon95 thanks for confirming it, do you mind making an official 0.5.6 or 0.5.7 and mark the other tags as pre-release? that would be super helpful for package managers like homebrew. 🙏

**Comment by chenrui333** [comment]
thank you so much! 💯
