### ISSUE TITLE
Loops

### ISSUE THREAD

**Issue by hellsienna** [bokwoon95/wgo#14]
I just tried this on a program that writes to a config file on start. This causes wgo to restart the program, which causes the program to write to the config file again basically turning into a loop.

**Comment by bokwoon95** [comment]
you should include only the files you use to watch with [the -file flag](https://github.com/bokwoon95/wgo?tab=readme-ov-file#including-and-excluding-files). What language is the program in? For example, if writing a Python program

```shell
wgo -file .py ./my_program.py
```

This will exclude any file names that don't contain .py which would exclude the config file from triggering a reload

**Comment by hellsienna** [comment]
Thank you for taking the time to reply. The thing is, the config file is
what I want to monitor. I want the program to reload when changes are made
to the config file,

**Comment by hellsienna** [comment]
The language is Go

**Comment by bokwoon95** [comment]
You want to reload the program when the config file changes, and the program also writes to the config file on start making it eligible to trigger a reload again? I... don't think there's a way solve this. 

Have you considered not writing to the config file on start? Why does a program that reads from a config file also need to write to it?

**Comment by bokwoon95** [comment]
If the program *has* to write to the config file, there might not be a way to use wgo with it unfortunately.

**Comment by hellsienna** [comment]
Ok, thanks for the clarification.

**Comment by gwillem** [comment]
I got in a loop with https://github.com/a-h/templ (`templ generate` which converts *.templ to *.go files), not sure how to fix.

**Comment by bokwoon95** [comment]
Sorry I didn't see your question until now, you need to exclude `_templ.go` files from triggering a `templ generate` because `templ generate` generates `_templ.go` files which causes a loop. It's mentioned here in the temps documentation: [https://templ.guide/developer-tools/live-reload/#alternative-1-wgo](https://templ.guide/developer-tools/live-reload/#alternative-1-wgo)

```shell
wgo -file=.go -file=.templ -xfile=_templ.go templ generate :: go run main.go
```

This is how your command should look:

```shell
wgo -verbose -file .sql sqlc generate :: wgo -verbose  -file .templ -xfile _templ.go templ generate :: wgo -verbose -file .go go run ./cmd/server
```

**Comment by bokwoon95** [comment]
Actually, your original command should be fine. 

- Only `.sql` files should trigger `sqlc generate`
- Only `.templ` files should trigger `templ generate`
- Only `.go` files should trigger `go run`. 

`sqlc generate` and `templ generate` both generate `.go` files, which should in turn cause `go run` to run at most once. I don't understand why it looping.

**Comment by bokwoon95** [comment]
Ohh I get it now, `wgo -file .sql sqlc generate` looks like it should only trigger on `.sql` files, but it actually triggers on `.go` files as well (causing the loop). Why? Because `sqlc generate` generates `.sql.go` files, which the the `.sql` regex also matches (it matches the ".sql" part of ".sql.go").

The fix is to explicitly exclude `.go` files from triggering sqlc generate:

```shell
wgo -verbose -file .sql -xfile .go sqlc generate :: wgo -verbose -file .templ -xfile _templ.go templ generate :: wgo -verbose -file .go go run ./cmd/server
```

Now *that* should work.

**Comment by gwillem** [comment]
Wow thanks @bokwoon95, that works amazingly well. 
Thanks for making wgo.
